// src/App.jsx
import React, { useState } from 'react'
import { changeTheme, supportCssVars, enableCssVars, themeVars } from './theme'
import Todo from './views/Todo'
import tagVars from './theme/Tag'
import todoVars from './theme/Todo'
import './style/app.css'

export default () => {
  const [todoColor, setTodoColor] = useState(() => themeVars(Object.keys(todoVars)[0]))
  const [tagColor, setTagColor] = useState(() => themeVars(Object.keys(tagVars)[0]))
  const [fontSize, setFontSize] = useState(() => themeVars('aui-font-size'))
  const [theme, setTheme] = useState(themeVars())
  const [title] = useState('New Tag')

  const change = e => {
    const apply = () => {
      const { name, value } = e.target

      name === 'aui-tag-color' && setTagColor(value)
      name === 'aui-todo-color' && setTodoColor(value)
      name === 'aui-font-size' && setFontSize(value)

      setTheme(Object.assign(theme, { [name]: value }))
      changeTheme(theme)
    }

    if (!supportCssVars() && window.confirm('当前浏览器不支持主题切换，要启用兼容程序吗？')) {
      enableCssVars().then(apply)
    } else {
      apply()
    }
  }

  return (
    <div id="app">
      <div id="nav">
        <span>更改 Tag 颜色</span>
        <input name="aui-tag-color" type="color" size="4" value={tagColor} onChange={change} />
        <span>更改 {title} 颜色</span>
        <input name="aui-todo-color" type="color" size="4" value={todoColor} onChange={change} />
        <span>更改字体大小</span>
        <input name="aui-font-size" type="text" size="2" value={fontSize} onChange={change} />
      </div>
      <Todo />
    </div>
  )
}

// src/App.vue
<template>
  <div id="app">
    <div id="nav">
      <span>更改 Tag 颜色</span>
      <input name="aui-tag-color" type="color" size="4" :value="tagColor" @change="change" />
      <span>更改 {{ title }} 颜色</span>
      <input :name="name" type="color" size="4" :value="color" @change="change" />
      <span>更改字体大小</span>
      <input name="aui-font-size" type="text" size="2" :value="fontSize" @change="change" />
    </div>
    <todo @loadCard="loadCard" />
  </div>
</template>

<script>
import Todo from './views/Todo.vue'
import { cssVars as tagVars } from './vue/Tag'
import { cssVars as todoVars } from './vue/Todo'
import { changeTheme, supportCssVars, enableCssVars, themeVars, combineVars, onResize } from './theme'
import './style/app.css'

export default {
  components: {
    Todo
  },
  data() {
    return {
      theme: {},
      title: 'New Tag',
      name: 'aui-todo-color',
      color: themeVars(Object.keys(todoVars)[0]),
      tagColor: themeVars(Object.keys(tagVars)[0]),
      fontSize: themeVars('aui-font-size')
    }
  },
  methods: {
    change(e) {
      const apply = () => {
        this.theme[e.target.name] = e.target.value
        changeTheme(this.theme)
      }

      if (!supportCssVars() && window.confirm('当前浏览器不支持主题切换，要启用兼容程序吗？')) {
        enableCssVars().then(apply)
      } else {
        apply()
      }
    },
    loadCard(cssVars) {
      if (cssVars) {
        combineVars(cssVars)
        this.title = 'Card'
        this.name = Object.keys(cssVars)[0]
        this.color = cssVars[this.name]
      }
    }
  },
  mounted() {
    onResize({
      check: () => (document.body.clientWidth < 768 ? 'mobile' : 'pc'),
      change: mode => (this.$mode.value = mode)
    })
  }
}
</script>
